# Generated by Django 6.0.4 on 2026-05-26 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('break', 'On Break')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
