# Generated by Django 6.0.4 on 2026-05-11 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('Analgesics', 'Analgesics / Painkillers'), ('Antibiotics', 'Antibiotics'), ('Antimalarials', 'Antimalarials'), ('Vitamins', 'Vitamins & Supplements'), ('First Aid', 'First Aid'), ('General', 'General Items')], default='General', max_length=100),
        ),
        migrations.CreateModel(
            name='MedicineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Restock', 'Restock'), ('Correction', 'Manual Correction'), ('Damage', 'Damaged/Expired Removal'), ('Sale', 'Sale')], max_length=20)),
                ('quantity_changed', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.medicine')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
